"""Initial migration.

Revision ID: 659874e200a4
Revises: 
Create Date: 2020-04-06 04:04:05.340973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659874e200a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todos')
    # ### end Alembic commands ###
